# Generated by Django 5.0.4 on 2024-04-26 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Type',
            field=models.CharField(default='MISC', max_length=5, verbose_name=[('REC', 'Records'), ('CL', 'Clothing'), ('PO', 'Posters'), ('MISC', 'Miscellaneous')]),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
