# Generated by Django 5.0.4 on 2024-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_type_listings_description_listings_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='Type',
            field=models.CharField(choices=[('REC', 'Records'), ('CL', 'Clothing'), ('PO', 'Posters'), ('MISC', 'Miscellaneous')], default='MISC', max_length=5),
        ),
    ]
