# Generated by Django 5.0.4 on 2024-04-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listings_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Type',
            new_name='type',
        ),
    ]
